name: Pull Build Test

# Ensure only one run per workflow + ref; cancel older in-progress runs on new commits
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"

      - name: Install dependencies
        shell: bash
        run: |
          npm ci

      - name: Run tests (Ubuntu)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          xvfb-run -a npm test

      - name: Run tests (Windows/macOS)
        if: runner.os != 'Linux'
        shell: bash
        run: |
          npm test
